### ISSUE TITLE
Новые боковые отступы

### ISSUE THREAD

**Issue by artemvasilkin** [webliumteam/blocks#3937]
- [ ] **1. Заменить переменную**

```CSS
    padding: var(--ui-content-gutter);
```
на
```SCSS
    padding: 0 var(--ui-content-gutter-default);

    @media (--ui-phone-devices) {
      padding: 0 var(--ui-content-gutter-480);
    }

    @media (--ui-tablet-devices) {
      padding: 0 var(--ui-content-gutter-768);
    }

    @media (--ui-medium-devices) {
      padding: 0 var(--ui-content-gutter-992);
    }

    @media (--ui-large-devices) {
      padding: 0 var(--ui-content-gutter-1280);
    }
```

- [ ] **2. Исправить минусовые `margin`'ы**

- [ ] **3. Исправить ветки, где нет переменной `var(--ui-content-gutter)`**

1. w/series-1/extra-counter/dev
2. w/series-1/raw-html/dev
3. w/series-1/stub/dev
4. w/series-12/cta/dev
5. w/series-13/header/dev
6. w/series-16/header/dev
7. w/series-17/header/dev
8. w/series-19/why/dev
9. w/series-2/header/dev
10. w/series-3/header/dev
11. w/series-4/cover/dev
12. w/series-5/cta/dev
13. w/series-6/cover/dev
14. w/series-6/header/dev
15. w/series-7/cta/dev
